= Demo: Identity Managment with Atomic Hosts
Christoph Görn <goern@redhat.com>
0.1.0, 2016-02-12

== Prerequisites

This demo requires https://vagrantup.com/[Vagrant] and libvirt to be installed. The Vagrant plugin
https://github.com/smdahlen/vagrant-hostmanager[hostmanager] must be installed too.

WARNING: initial provisioning of the IdM server will install a significant
amount of RPM, a little bit of time is required.

== Objectives

This demo will show how to use Vagrant to set up a complete demo environment
include an Identity Management (IdM) Service and a few clients using the service.

You will see how to provision an Atomic Host and enroll it with the IdM service,
how to provision OpenShift Origin and use LDAP as a backend for groups.

Web User Interfaces for all three virtual machines, IdM service and OpenShift
Origin will be available and give an impression of the usability of the whole
environment.

== Usage

The main tool within this demo is vagrant, it will be used to spin up a set
of hosts, all are based on Fedora 23:

1. idm-1 - an Identity Management service
2. atomic-host-1 - a client, which will be enrolled during the course of the demo
3. oso-1 - an all in one installation of OpenShift Origin, it is configured to use the IdM service

After preparing the demo, you will be able to have a look at

a. Cockpit
b. freeIPA web UI
c. OpenShift Origin web console

=== Preparation - provision IdM

The first step is to provision the IdM service. Using

[source,bash]
vagrant up idm-1

you can create and provision a freeIPA server, based on Fedora 23. It will provide a
web user interface.

As the hostmanager Vagrant plugin is installed, `/etc/hosts` of the host machine
will be reconfigured after creation of the idm-1 virtual machine.

Please use your browser to navigate to `idm-1.goern.example.com` and use _admin_
as the username and _foobarfoo_ as the password to sign in.

When browsing the list of hosts known by IdM you will notice that only
`idm-1.goern.example.com` is currently available. This will change after the
next step has finished.

=== provision and enroll an Atomic Host
